site_name: Juiey
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 调整到深色模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 调整到明亮模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.top
  icon:
    annotation: material/chevron-right-circle
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Juiey/study

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 马克思主义原理:
      - 马克思主义原理/物质与意识的辩证关系.md
      - 马克思主义原理/对立统一规律是事物发展的根本规律.md
      - 马克思主义原理/量变质变规律和否定之否定规律.md
      - 马克思主义原理/唯物辩证法是科学的认识方法.md
      - 马克思主义原理/实践的本质与基本结构.md
      - 马克思主义原理/实践与认识的辩证运动及其规律.md
      - 马克思主义原理/两次飞跃.md
      - 马克思主义原理/真理与价值的辩证统一.md
      - 马克思主义原理/社会存在和社会意识的辩证关系.md
      - 马克思主义原理/人民群众在创造历史过程中的决定作用.md
      - 马克思主义原理/商品的二因素和生产商品的劳动的二重性.md
      - 马克思主义原理/价值规律及其作用.md
      - 马克思主义原理/劳动力成为商品与货币转化为资本.md
      - 马克思主义原理/生产剩余价值是资本主义生产方式的绝对规律.md
      - 马克思主义原理/资本主义的基本矛盾.md
      - 马克思主义原理/资本主义的经济危机.md
      - 马克思主义原理/资本主义经济危机的周期性.md
      - 马克思主义原理/经济全球化及其影响.md
      - 马克思主义原理/共产主义社会的基本特征总结.md
  - 操作系统:
      - 操作系统/index.md
      - 操作系统/课件.md
      - 操作系统引论:
          - 操作系统/操作系统引论/操作系统概念.md
          - 操作系统/操作系统引论/操作系统的特征和作用.md
      - 进程管理:
          - 操作系统/进程管理/程序的顺序执行和并发执行.md
          - 操作系统/进程管理/进程的概念.md
          - 操作系统/进程管理/进程的状态.md
          - 操作系统/进程管理/进程的组成.md
          - 操作系统/进程管理/线程的概念.md
          - 操作系统/进程管理/线程的状态.md
          - 操作系统/进程管理/进程的控制.md
          - 操作系统/进程管理/进程的同步.md
          - 操作系统/进程管理/进程的互斥.md
          - 操作系统/进程管理/临界资源和临界区.md
          - 操作系统/进程管理/信号量与PV操作.md
          - 操作系统/进程管理/时间同步问题.md
      - 死锁:
          - 操作系统/死锁/死锁的概念.md
          - 操作系统/死锁/死锁的处理策略.md
          - 操作系统/死锁/死锁的预防.md
          - 操作系统/死锁/死锁的避免.md
          - 操作系统/死锁/死锁的检测.md
          - 操作系统/死锁/死锁的解除.md
          - 操作系统/死锁/死锁的综合处理策略.md
          - 操作系统/死锁/线程死锁.md
      - 中断与处理机调度:
          - 操作系统/中断与处理机调度/中断概述.md
          - 操作系统/中断与处理机调度/进程调度目标和调度方式.md
          - 操作系统/中断与处理机调度/调度算法的评价准则.md
          - 操作系统/中断与处理机调度/三级调度体系.md
          - 操作系统/中断与处理机调度/作业调度.md
          - 操作系统/中断与处理机调度/进程调度.md
          - 操作系统/中断与处理机调度/线程调度.md
      - 存储管理:
          - 操作系统/存储管理/存储管理概述.md
          - 操作系统/存储管理/程序的装入.md
          - 操作系统/存储管理/程序的链接.md
          - 操作系统/存储管理/连续存储管理.md
          - 操作系统/存储管理/页式存储管理.md
          - 操作系统/存储管理/段式存储管理.md
          - 操作系统/存储管理/分页和分段存储管理的主要区别.md
          - 操作系统/存储管理/段页式存储管理.md
          - 操作系统/存储管理/虚拟存储管理方式.md
          - 操作系统/存储管理/页面置换算法.md
      - 设备管理:
          - 操作系统/设备管理/设备管理概述.md
          - 操作系统/设备管理/输入输出系统.md
          - 操作系统/设备管理/输入输出的控制方式.md
          - 操作系统/设备管理/缓冲技术.md
          - 操作系统/设备管理/设备分配技术.md
          - 操作系统/设备管理/磁盘管理.md
      - 文件管理:
          - 操作系统/文件管理/文件管理概述.md
          - 操作系统/文件管理/文件的组织结构和存取方式.md
          - 操作系统/文件管理/目录管理.md
          - 操作系统/文件管理/文件的使用.md
          - 操作系统/文件管理/文件的共享.md
          - 操作系统/文件管理/文件的保护与保密.md
      - 作业管理与用户接口:
          - 操作系统/作业管理与用户接口/作业管理概述.md
          - 操作系统/作业管理与用户接口/批处理作业的管理.md
          - 操作系统/作业管理与用户接口/批处理作业调度算法.md
          - 操作系统/作业管理与用户接口/交互式作业的控制与管理.md
          - 操作系统/作业管理与用户接口/操作系统与用户的接口.md
  - 毛泽东思想与中国特色社会主义理论体系概论:
      - 毛泽东思想与中国特色社会主义理论体系概论/index.md
      - 毛泽东思想与中国特色社会主义理论体系概论:
          - 毛泽东思想与中国特色社会主义理论体系概论/马克思主义中国化时代化的历史进程与理论成果/提出.md
          - 毛泽东思想与中国特色社会主义理论体系概论/马克思主义中国化时代化的历史进程与理论成果/内涵.md
          - 毛泽东思想与中国特色社会主义理论体系概论/马克思主义中国化时代化的历史进程与理论成果/历史进程.md
          - 毛泽东思想与中国特色社会主义理论体系概论/马克思主义中国化时代化的历史进程与理论成果/理论成果及其关系.md
      - 毛泽东思想及其历史地位:
          - 毛泽东思想与中国特色社会主义理论体系概论/毛泽东思想及其历史地位/毛泽东思想的形成和发展.md
          - 毛泽东思想与中国特色社会主义理论体系概论/毛泽东思想及其历史地位/主要内容.md
          - 毛泽东思想与中国特色社会主义理论体系概论/毛泽东思想及其历史地位/活的灵魂.md
          - 毛泽东思想与中国特色社会主义理论体系概论/毛泽东思想及其历史地位/历史地位.md
      - 新民主主义革命理论:
          - 毛泽东思想与中国特色社会主义理论体系概论/新民主主义革命理论/形成的依据.md
          - 毛泽东思想与中国特色社会主义理论体系概论/新民主主义革命理论/总路线.md
          - 毛泽东思想与中国特色社会主义理论体系概论/新民主主义革命理论/基本纲领.md
          - 毛泽东思想与中国特色社会主义理论体系概论/新民主主义革命理论/道路和基本经验.md
      - 社会主义改造理论:
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义改造理论/从新民主主义到社会主义的转变.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义改造理论/社会主义改造道路和历史经验.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义改造理论/社会主义基本制度在中国的确立.md
      - 社会主义建设道路初步探索的理论成果:
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义建设道路初步探索的理论成果/调动一切积极因素为社会主义事业服务.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义建设道路初步探索的理论成果/正确认识和处理社会主义社会矛盾的思想.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义建设道路初步探索的理论成果/走中国工业化道路的思想.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义建设道路初步探索的理论成果/初步探索的其他理论成果.md
          - 毛泽东思想与中国特色社会主义理论体系概论/社会主义建设道路初步探索的理论成果/初步探索的意义和经验教训.md
      - 中国特色社会主义理论体系的形成发展:
          - 毛泽东思想与中国特色社会主义理论体系概论/中国特色社会主义理论体系的形成发展/国际背景.md
          - 毛泽东思想与中国特色社会主义理论体系概论/中国特色社会主义理论体系的形成发展/社会历史条件.md
          - 毛泽东思想与中国特色社会主义理论体系概论/中国特色社会主义理论体系的形成发展/实践基础.md
          - 毛泽东思想与中国特色社会主义理论体系概论/中国特色社会主义理论体系的形成发展/形成发展过程.md
      - 邓小平理论:
          - 毛泽东思想与中国特色社会主义理论体系概论/邓小平理论/首要的基本的理论问题.md
          - 毛泽东思想与中国特色社会主义理论体系概论/邓小平理论/精髓.md
          - 毛泽东思想与中国特色社会主义理论体系概论/邓小平理论/主要内容.md
          - 毛泽东思想与中国特色社会主义理论体系概论/邓小平理论/历史地位.md
      - 三个代表重要思想:
          - 毛泽东思想与中国特色社会主义理论体系概论/三个代表重要思想/核心观点.md
          - 毛泽东思想与中国特色社会主义理论体系概论/三个代表重要思想/主要内容.md
          - 毛泽东思想与中国特色社会主义理论体系概论/三个代表重要思想/历史地位.md
      - 科学发展观:
          - 毛泽东思想与中国特色社会主义理论体系概论/科学发展观/科学发展观的科学内涵.md
          - 毛泽东思想与中国特色社会主义理论体系概论/科学发展观/科学发展观的主要内容.md
          - 毛泽东思想与中国特色社会主义理论体系概论/科学发展观/科学发展观的历史地位.md
  - 习近平新时代中国特色社会主义思想概论:
          - 习近平新时代中国特色社会主义思想概论/导论.md
          - 习近平新时代中国特色社会主义思想概论/新时代坚持和发展中国特色社会主义.md
          - 习近平新时代中国特色社会主义思想概论/以中国式现代化全面推进中华民族伟大复兴.md
          - 习近平新时代中国特色社会主义思想概论/坚持党的全面领导.md
          - 习近平新时代中国特色社会主义思想概论/坚持以人民为中心.md
          - 习近平新时代中国特色社会主义思想概论/全面深化改革开放.md
          - 习近平新时代中国特色社会主义思想概论/推动高质量发展.md
          - 习近平新时代中国特色社会主义思想概论/社会主义现代化建设的教育、科技、人才战略.md
          - 习近平新时代中国特色社会主义思想概论/发展全过程人民民主.md
          - 习近平新时代中国特色社会主义思想概论/全面依法治国.md
          - 习近平新时代中国特色社会主义思想概论/建设社会主义文化强国.md
          - 习近平新时代中国特色社会主义思想概论/以保障和改善民生为重点加强社会建设.md
          - 习近平新时代中国特色社会主义思想概论/建设社会主义生态文明.md
          - 习近平新时代中国特色社会主义思想概论/维护和塑造国家安全.md
          - 习近平新时代中国特色社会主义思想概论/建设巩固国防和强大人民军队.md
          - 习近平新时代中国特色社会主义思想概论/坚持“一国两制”和推进祖国完全统一.md
          - 习近平新时代中国特色社会主义思想概论/全面从严治党.md






plugins:
  - search:
      lang:
        - zh
        - zh-Hant
        - en
  - i18n:
      docs_structure: suffix
      reconfigure_search: true
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

        - locale: zh-Hant
          name: 繁體中文
          build: true
          nav:
            - 馬克思主義原理:
                - 物質與意識的辯證關係: 马克思主义原理/物质与意识的辩证关系.zh-Hant.md
                - 對立統一規律是事物發展的根本規律: 马克思主义原理/对立统一规律是事物发展的根本规律.zh-Hant.md
                - 量質變規律和否定之否定規律: 马克思主义原理/量变质变规律和否定之否定规律.zh-Hant.md
                - 唯物辯證法是科學的認識方法: 马克思主义原理/唯物辩证法是科学的认识方法.zh-Hant.md
                - 實踐的本質與基本結構: 马克思主义原理/实践的本质与基本结构.zh-Hant.md
                - 實踐與認識的辯證運動及其規律: 马克思主义原理/实践与认识的辩证运动及其规律.zh-Hant.md
                - 兩次飛躍: 马克思主义原理/两次飞跃.zh-Hant.md
                - 真理與價值的辯證統一: 马克思主义原理/真理与价值的辩证统一.zh-Hant.md
                - 社會存在與社會意識的辯證關係: 马克思主义原理/社会存在和社会意识的辩证关系.zh-Hant.md
                - 群众在創造歷史過程中的決定作用: 马克思主义原理/人民群众在创造历史过程中的决定作用.zh-Hant.md
                - 商品和生產商品的勞動的二重性: 马克思主义原理/商品的二因素和生产商品的劳动的二重性.zh-Hant.md
                - 价值規律及其作用: 马克思主义原理/价值规律及其作用.zh-Hant.md
                - 劳动力成為商品與貨幣轉化為資本: 马克思主义原理/劳动力成为商品与货币转化为资本.zh-Hant.md
                - 生產剩余價值是資本主義生產方式的絕對規律: 马克思主义原理/生产剩余价值是资本主义生产方式的绝对规律.zh-Hant.md
                - 資本主義的基本矛盾: 马克思主义原理/资本主义的基本矛盾.zh-Hant.md
                - 資本主義的經濟危機: 马克思主义原理/资本主义的经济危机.zh-Hant.md
                - 資本主義經濟危機的周期性: 马克思主义原理/资本主义经济危机的周期性.zh-Hant.md
                - 經濟全球化及其影響: 马克思主义原理/经济全球化及其影响.zh-Hant.md
                - 共産主義社會的基本特徵: 马克思主义原理/共产主义社会的基本特征总结.zh-Hant.md
            - 操作系統:
                - 操作系统/index.zh-Hant.md
                - 課件: 操作系统/课件.zh-Hant.md
                - 操作系統引論:
                    - 操作系統的特徵和作用: 操作系统/操作系统引论/操作系统的特征和作用.zh-Hant.md
                    - 操作系統的概念: 操作系统/操作系统引论/操作系统概念.zh-Hant.md
                - 進程管理:
                    - 程序的順序執行和並發執行: 操作系统/进程管理/程序的顺序执行和并发执行.zh-Hant.md
                    - 進程的概念: 操作系统/进程管理/进程的概念.zh-Hant.md
                    - 進程的狀態: 操作系统/进程管理/进程的状态.zh-Hant.md
                    - 進程的狀態: 操作系统/进程管理/进程的状态.zh-Hant.md
                    - 進程的組成: 操作系统/进程管理/进程的组成.zh-Hant.md
                    - 線程的概念: 操作系统/进程管理/线程的概念.zh-Hant.md
                    - 線程的狀態: 操作系统/进程管理/线程的状态.zh-Hant.md
                    - 進程的控制: 操作系统/进程管理/进程的控制.zh-Hant.md
                    - 進程的同步: 操作系统/进程管理/进程的同步.zh-Hant.md
                    - 進程的互斥: 操作系统/进程管理/进程的互斥.zh-Hant.md
                    - 臨界資源和臨界區: 操作系统/进程管理/临界资源和临界区.zh-Hant.md
                    - 信號量與PV操作: 操作系统/进程管理/信号量与PV操作.zh-Hant.md
                    - 時間同步問題: 操作系统/进程管理/时间同步问题.zh-Hant.md
                - 死鎖:  
                    - 死鎖的概念: 操作系统/死锁/死锁的概念.zh-Hant.md  
                    - 死鎖的處理策略: 操作系统/死锁/死锁的处理策略.zh-Hant.md  
                    - 死鎖的預防: 操作系统/死锁/死锁的预防.zh-Hant.md  
                    - 死鎖的避免: 操作系统/死锁/死锁的避免.zh-Hant.md  
                    - 死鎖的檢測: 操作系统/死锁/死锁的检测.zh-Hant.md  
                    - 死鎖的解除: 操作系统/死锁/死锁的解除.zh-Hant.md  
                    - 死鎖的綜合處理策略: 操作系统/死锁/死锁的综合处理策略.zh-Hant.md  
                    - 線程死鎖: 操作系统/死锁/线程死锁.zh-Hant.md  
                - 中斷與處理機調度:  
                    - 中斷概述: 操作系统/中断与处理机调度/中断概述.zh-Hant.md  
                    - 進程調度目標和調度方式: 操作系统/中断与处理机调度/进程调度目标和调度方式.zh-Hant.md  
                    - 調度算法的評價準則: 操作系统/中断与处理机调度/调度算法的评价准则.zh-Hant.md  
                    - 三級調度體系: 操作系统/中断与处理机调度/三级调度体系.zh-Hant.md  
                    - 作業調度: 操作系统/中断与处理机调度/作业调度.zh-Hant.md  
                    - 進程調度: 操作系统/中断与处理机调度/进程调度.zh-Hant.md  
                    - 線程調度: 操作系统/中断与处理机调度/线程调度.zh-Hant.md  
                - 存儲管理:  
                    - 存儲管理概述: 操作系统/存储管理/存储管理概述.zh-Hant.md  
                    - 程序的裝入: 操作系统/存储管理/程序的装入.zh-Hant.md  
                    - 程序的鏈接: 操作系统/存储管理/程序的链接.zh-Hant.md  
                    - 連續存儲管理: 操作系统/存储管理/连续存储管理.zh-Hant.md  
                    - 頁式存儲管理: 操作系统/存储管理/页式存储管理.zh-Hant.md  
                    - 段式存儲管理: 操作系统/存储管理/段式存储管理.zh-Hant.md  
                    - 分頁和分段存儲管理的主要區別: 操作系统/存储管理/分页和分段存储管理的主要区别.zh-Hant.md  
                    - 段頁式存儲管理: 操作系统/存储管理/段页式存储管理.zh-Hant.md  
                    - 虛擬存儲管理方式: 操作系统/存储管理/虚拟存储管理方式.zh-Hant.md  
                    - 頁面置換算法: 操作系统/存储管理/页面置换算法.zh-Hant.md  
                - 設備管理:  
                    - 設備管理概述: 操作系统/设备管理/设备管理概述.zh-Hant.md  
                    - 輸入輸出系統: 操作系统/设备管理/输入输出系统.zh-Hant.md  
                    - 輸入輸出的控制方式: 操作系统/设备管理/输入输出的控制方式.zh-Hant.md  
                    - 緩衝技術: 操作系统/设备管理/缓冲技术.zh-Hant.md  
                    - 設備分配技術: 操作系统/设备管理/设备分配技术.zh-Hant.md  
                    - 磁盤管理: 操作系统/设备管理/磁盘管理.zh-Hant.md  
                - 文件管理:  
                    - 文件管理概述: 操作系统/文件管理/文件管理概述.zh-Hant.md  
                    - 文件的組織結構和存取方式: 操作系统/文件管理/文件的组织结构和存取方式.zh-Hant.md  
                    - 目錄管理: 操作系统/文件管理/目录管理.zh-Hant.md  
                    - 文件的使用: 操作系统/文件管理/文件的使用.zh-Hant.md  
                    - 文件的共享: 操作系统/文件管理/文件的共享.zh-Hant.md  
                    - 文件的保護與保密: 操作系统/文件管理/文件的保护与保密.zh-Hant.md  
                - 作業管理與用戶接口:  
                    - 作業管理概述: 操作系统/作业管理与用户接口/作业管理概述.zh-Hant.md  
                    - 批處理作業的管理: 操作系统/作业管理与用户接口/批处理作业的管理.zh-Hant.md  
                    - 批處理作業調度算法: 操作系统/作业管理与用户接口/批处理作业调度算法.zh-Hant.md  
                    - 交互式作業的控制與管理: 操作系统/作业管理与用户接口/交互式作业的控制与管理.zh-Hant.md  
                    - 操作系統與用戶的接口: 操作系统/作业管理与用户接口/操作系统与用户的接口.zh-Hant.md  


        - locale: en
          name: English
          build: true
          nav:
            - Principles of Marxism:
                - The Dialectical Relationship Between Matter and Consciousness: 马克思主义原理/物质与意识的辩证关系.en.md
                - The Law of the Unity of Opposites as the Fundamental Law of the Development of Things: 马克思主义原理/对立统一规律是事物发展的根本规律.en.md
                - The Laws of the Transformation of Quantity into Quality and the Negation of the Negation: 马克思主义原理/量变质变规律和否定之否定规律.en.md
                - Material Dialectics is a Dcientific Ethod of Cognition: 马克思主义原理/唯物辩证法是科学的认识方法.en.md
                - The Essence and Basic Structure of Practice: 马克思主义原理/实践的本质与基本结构.en.md
                - The Dialectical Movement and Laws of Practice and Knowledge: 马克思主义原理/实践与认识的辩证运动及其规律.en.md
                - The Two Leaps: 马克思主义原理/两次飞跃.en.md
                - The Dialectical Unity of Truth and Value: 马克思主义原理/真理与价值的辩证统一.en.md
                - The Dialectical Relationship Between Social Being and Social Consciousness: 马克思主义原理/社会存在和社会意识的辩证关系.en.md
                - The Decisive Role of the People in the Process of Creating History: 马克思主义原理/人民群众在创造历史过程中的决定作用.en.md
                - The Two Factors of Commodities and the Dual Character of Labor Producing Commodities: 马克思主义原理/商品的二因素和生产商品的劳动的二重性.en.md
                - The Law of Value and Its Function: 马克思主义原理/价值规律及其作用.en.md
                - Labor Power as a Commodity and the Transformation of Money into Capital: 马克思主义原理/劳动力成为商品与货币转化为资本.en.md
                - The Production of Surplus Value as the Absolute Law of the Capitalist Mode of Production: 马克思主义原理/生产剩余价值是资本主义生产方式的绝对规律.en.md
                - The Basic Contradictions of Capitalism: 马克思主义原理/资本主义的基本矛盾.en.md
                - The Economic Crisis of Capitalism: 马克思主义原理/资本主义的经济危机.en.md
                - The Cyclical Nature of Capitalist Economic Crises: 马克思主义原理/资本主义经济危机的周期性.en.md
                - Economic Globalization and Its Impact: 马克思主义原理/经济全球化及其影响.en.md
                - Summary of the Basic Characteristics of a Communist Society: 马克思主义原理/共产主义社会的基本特征总结.en.md
            - Operating System:
                - 操作系统/index.en.md
                - Courseware: 操作系统/课件.en.md
                - Operating System Introduction:
                    - Characteristics and Functions of Operating Systems: 操作系统/操作系统引论/操作系统的特征和作用.en.md
                    - Concepts of Operating Systems: 操作系统/操作系统引论/操作系统概念.en.md
                - Process Management:
                    - Sequential and Concurrent Program Execution: 操作系统/进程管理/程序的顺序执行和并发执行.en.md
                    - Process Concepts: 操作系统/进程管理/进程的概念.en.md
                    - Process States: 操作系统/进程管理/进程的状态.en.md
                    - Process Composition: 操作系统/进程管理/进程的组成.en.md
                    - Thread Concepts: 操作系统/进程管理/线程的概念.en.md
                    - Thread States: 操作系统/进程管理/线程的状态.en.md
                    - Process Control: 操作系统/进程管理/进程的控制.en.md
                    - Process Synchronization: 操作系统/进程管理/进程的同步.en.md
                    - Process Mutual Exclusion: 操作系统/进程管理/进程的互斥.en.md
                    - Critical Resources and Critical Sections: 操作系统/进程管理/临界资源和临界区.en.md
                    - Semaphores and PV Operations: 操作系统/进程管理/信号量与PV操作.en.md
                    - Time Synchronization Problems: 操作系统/进程管理/时间同步问题.en.md
                - Deadlock:
                    - Deadlock Concepts: 操作系统/死锁/死锁的概念.en.md
                    - Deadlock Handling Strategies: 操作系统/死锁/死锁的处理策略.en.md
                    - Deadlock Prevention: 操作系统/死锁/死锁的预防.en.md
                    - Deadlock Avoidance: 操作系统/死锁/死锁的避免.en.md
                    - Deadlock Detection: 操作系统/死锁/死锁的检测.en.md
                    - Deadlock Recovery: 操作系统/死锁/死锁的解除.en.md
                    - Comprehensive Deadlock Handling Strategies: 操作系统/死锁/死锁的综合处理策略.en.md
                    - Thread Deadlock: 操作系统/死锁/线程死锁.en.md
                - Interrupts and Processor Scheduling:
                    - Interrupt Overview: 操作系统/中断与处理机调度/中断概述.en.md
                    - Process Scheduling Goals and Methods: 操作系统/中断与处理机调度/进程调度目标和调度方式.en.md
                    - Scheduling Algorithm Evaluation Criteria: 操作系统/中断与处理机调度/调度算法的评价准则.en.md
                    - Three-Level Scheduling System: 操作系统/中断与处理机调度/三级调度体系.en.md
                    - Job Scheduling: 操作系统/中断与处理机调度/作业调度.en.md
                    - Process Scheduling: 操作系统/中断与处理机调度/进程调度.en.md
                    - Thread Scheduling: 操作系统/中断与处理机调度/线程调度.en.md
                - Memory Management:
                    - Memory Management Overview: 操作系统/存储管理/存储管理概述.en.md
                    - Program Loading: 操作系统/存储管理/程序的装入.en.md
                    - Program Linking: 操作系统/存储管理/程序的链接.en.md
                    - Contiguous Memory Management: 操作系统/存储管理/连续存储管理.en.md
                    - Paged Memory Management: 操作系统/存储管理/页式存储管理.en.md
                    - Segmented Memory Management: 操作系统/存储管理/段式存储管理.en.md
                    - Main Differences Between Paging and Segmentation: 操作系统/存储管理/分页和分段存储管理的主要区别.en.md
                    - Segmented Paging Memory Management: 操作系统/存储管理/段页式存储管理.en.md
                    - Virtual Memory Management Methods: 操作系统/存储管理/虚拟存储管理方式.en.md
                    - Page Replacement Algorithms: 操作系统/存储管理/页面置换算法.en.md
                - Device Management:
                    - Device Management Overview: 操作系统/设备管理/设备管理概述.en.md
                    - Input/Output System: 操作系统/设备管理/输入输出系统.en.md
                    - Input/Output Control Methods: 操作系统/设备管理/输入输出的控制方式.en.md
                    - Buffering Techniques: 操作系统/设备管理/缓冲技术.en.md
                    - Device Allocation Techniques: 操作系统/设备管理/设备分配技术.en.md
                    - Disk Management: 操作系统/设备管理/磁盘管理.en.md
                - File Management:
                    - File Management Overview: 操作系统/文件管理/文件管理概述.en.md
                    - File Organization Structure and Access Methods: 操作系统/文件管理/文件的组织结构和存取方式.en.md
                    - Directory Management: 操作系统/文件管理/目录管理.en.md
                    - File Usage: 操作系统/文件管理/文件的使用.en.md
                    - File Sharing: 操作系统/文件管理/文件的共享.en.md
                    - File Protection and Security: 操作系统/文件管理/文件的保护与保密.en.md
                - Job Management and User Interface:
                    - Job Management Overview: 操作系统/作业管理与用户接口/作业管理概述.en.md
                    - Batch Job Management: 操作系统/作业管理与用户接口/批处理作业的管理.en.md
                    - Batch Job Scheduling Algorithms: 操作系统/作业管理与用户接口/批处理作业调度算法.en.md
                    - Interactive Job Control and Management: 操作系统/作业管理与用户接口/交互式作业的控制与管理.en.md
                    - Operating System and User Interface: 操作系统/作业管理与用户接口/操作系统与用户的接口.en.md
            

copyright: Copyright &copy; 2025 Juiey
